### ISSUE TITLE
Not working, totally this plugin is waste

### ISSUE THREAD

**Issue by merbin2012** [byorty/cordova-install-referrer-api#2]
I tried to implement this and live to the play store, but it always return this "utm_source=google-play&utm_medium=organic", if we pass any extra argument, it will return the following "utm_source=(not%20set)&utm_medium=(not%20set)".
Kindly remove, if it is not working. Not working for me. if you have any solution, please give.

**Comment by peppyday** [comment]
its working for me

**Comment by merbin2012** [comment]
@peppyday 0.1% only it returns the result, may I know how will you get the result? I am using App center and Firebase analytics

**Comment by peppyday** [comment]
i don't use analytics.. just this plugin. in the link you must include 'referrer' else you will get this error. eg
https://play.google.com/store/apps/details?id=com.package.name&referrer=utm_source%3D1234567891%26utm_medium%3D1234567891

**Comment by merbin2012** [comment]
I'm using Appcenter to track the referrals, see the below screenshot. 99.9% install refferal from google, but many installs I'm getting from other sources too. But they are not showing.

![Screenshot_2020-07-07-00-03-20-171_com android chrome](https://user-images.githubusercontent.com/3687184/86627482-0970eb80-bfe6-11ea-8e6c-4433e68f1246.jpg)

**Comment by merbin2012** [comment]
> i don't use analytics.. just this plugin. in the link, you must include 'referrer' else you will get this error. eg https://play.google.com/store/apps/details?id=com.package.name&referrer=utm_source%3D1234567891%26utm_medium%3D1234567891

Thank you very much, my problem is solved. I am not used encodeURIComponent, that's why I faced this issue.
